Hotfix dd master error step
DTS-STN/virtual-assistant-protobot pull request #13
Opened 2022-02-24 00:45 UTC by binggaofw

# Description
update max retry to 2 
remove greeting part for callback bot 
integrate callback and unblock bot

## Checklist
- [ ] Update CHANGELOG.md
- [ ] Unit tests have been added/updated
- [ ] e2e tests have been added/updated

2022-02-24 21:53 UTC, gurunadhambuddepu approved these changes

2022-02-25 13:20 UTC, rajuchetlapalli commented on src/dialogs/callbackDialogs/getPreferredMethodOfContactStep.ts
>          // callbackBotDetails.confirmPhoneStep = null;
You can get rid of it. If you don't need it.

2022-02-25 13:42 UTC, rajuchetlapalli requested changes

2022-02-25 13:42 UTC, rajuchetlapalli commented on src/dialogs/callbackDialogs/getPreferredMethodOfContactStep.ts
>          // callbackBotDetails.confirmPhoneStep = null;
You can delete it If you don't need.

2022-02-25 13:42 UTC, rajuchetlapalli commented on src/dialogs/callbackDialogs/getPreferredMethodOfContactStep.ts
same here

2022-02-25 13:42 UTC, rajuchetlapalli commented on src/dialogs/callbackDialogs/getUserEmailStep.ts
same here

2022-02-25 13:42 UTC, rajuchetlapalli commented on src/dialogs/callbackDialogs/getUserPhoneNumberStep.ts
>              /^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$/im;
As per MH comments we are accepting only Canadian phone numbers for Proto bot.

2022-02-25 13:42 UTC, rajuchetlapalli commented on src/dialogs/unblockDialogs/unblockLookup.ts
>      // const recognizerResult = await recognizer.recognize(stepContext.context);
same here

2022-02-28 19:42 UTC, llakewood approved these changes

2022-03-04 12:59 UTC, llakewood approved these changes

2022-03-04 13:01 UTC, llakewood commented
I see that a lot of the Lint App code checks are failing due to changes of single and double quotes. Is there a reason that we are using the opposite quotes to the linting?

2022-03-04 15:45 UTC, binggaofw commented
> I see that a lot of the Lint App code checks are failing due to changes of single and double quotes. Is there a reason that we are using the opposite quotes to the linting?

I will change all double quotes to single one

2022-03-05 00:24 UTC, merged